version: 0.2

env:
  variables:
    CLUSTER: GreetCluster
    SERVICE: ServiceNewGreet
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=279766552404.dkr.ecr.us-east-1.amazonaws.com/greetservice
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - echo Build started on `date`
      - ./mvnw clean install package
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Updating ECS service
      - aws ecs update-service --cluster $CLUSTER --service $SERVICE --force-new-deployment